### PR TITLE
Updating images for issues # 13, 14, and 19

### PR DESCRIPTION
**Pull request by dctootall**
Updated screenshots for the User Management, Indexers, and Kit sections of the document.

### CODE REVIEW

**Comment by floren** [comment]
**Indexer:**

tags.png looks blurry in the resulting PDF

greece-accel.png, stats-accel.png are too wide; in the PDF, they end up hard to read. Compare to the originals, which have a taller aspect ratio.

**Kits:**

available-kits.png is also very wide, making it hard to read the kits, but that's less important given the context. Same for explore.png

buildwizard1.png is hard to read when printed out. Can you play with the window size a little? I don't mind losing the icon or cover selectors at the bottom of that page if it means the text appears larger elsewhere.

**Users:**

Looks fine!

**Comment by traetox** [comment]
because we need the images to be in light theme for a printable PDF, if you regenerate any images please do so in the light theme.

**Comment by dctootall** [comment]
I updated all the images with the light Theme.

**Review by traetox — APPROVED** [review]
LGTM

@floren only one that you might need to check is `Kits/images/upgradekit.png`.

I think it's fine, but you have "the touch"

**Review by floren — APPROVED** [review]

**Pull request merged**
